baseURL: "https://lpains.net/"
title: LPains.net
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-44645930-2

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: LPains.net
    description: "Pains of a geek"
    keywords: [Blog, Personal, LPains, Pains, .NET, Technology, Development, Code]
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["/images/lpains.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    hideDescription: true
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/images/favicon.ico"
        favicon16x16: "/images/favicon-16x16.png"
        favicon32x32: "/images/favicon-32x32.png"
        apple_touch_icon: "/images/apple-touch=icon.png"

    label:
        text: "LPains.net"
        # icon: "/images/apple-touch-icon.png"
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Pains
        subtitle: "Coder | Geek"
        imageUrl: "/images/lpains.jpg"
        imageWidth: 160
        imageHeight: 160
        imageTitle: gravatar
        # buttons:
        #     - name: Posts
        #       url: posts
        #     - name: Categories
        #       url: categories

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: twitter
          url: "https://twitter.com/lucas.pains"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/1462485/lpains"
        - name: github
          url: "https://github.com/jlucaspains"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: posts
          url: /posts/
          weight: 10
        - identifier: categories
          name: categories
          url: /categories/
          weight: 20
        - identifier: about
          name: about
          url: /about/
          weight: 30
        - identifier: terms
          name: terms
          url: /terms/
          weight: 40

#Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        noClasses: true
        codeFences: true
        # guessSyntax: true
        lineNos: true
        # style: monokai

publishDir: docs