baseURL: "/"
title: LPains
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Pains
    description: "Pains of a geek"
    keywords: [Blog, Personal, LPains, Pains, .NET, Technology, Development, Code]
    author: LPains
    # author: ["Me", "You"] # multiple authors
    images: ["/images/lpains.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    hideDescription: true
    showtoc: true
    tocopen: false

    assets:
        # disableFingerprinting: true
        favicon: "/images/favicon.ico"
        favicon16x16: "/images/favicon-16x16.png"
        favicon32x32: "/images/favicon-32x32.png"
        apple_touch_icon: "/images/apple-touch=icon.png"

    label:
        text: "LPains"
        # icon: "/images/apple-touch-icon.png"
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: lpains
        subtitle: "On the 'Pains' of building software"
        imageUrl: "/images/lpains.jpg"
        imageWidth: 160
        imageHeight: 160
        imageTitle: gravatar
        buttons:
        - name: Recent
          url: posts
        - name: Archive
          url: archive
        - name: Categories
          url: categories

    # home-info mode
    # homeInfoParams:
    #     Title: "lpains"
    #     Content: On the pains of building software

    socialIcons:
        - name: twitter
          url: "https://twitter.com/lucas.pains"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/1462485/lpains"
        - name: github
          url: "https://github.com/jlucaspains"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/jlucaspains/blog-v2/blob/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: search
          name: search
          url: /search/
          weight: 10
        - identifier: about
          name: about
          url: /about/
          weight: 30
        - identifier: terms
          name: terms
          url: /terms/
          weight: 40

#Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        noClasses: true
        codeFences: true
        # guessSyntax: true
        lineNos: true
        # style: monokai
  
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary